### ISSUE TITLE
Enhancement: gradient for severity options 

### ISSUE THREAD

**Issue by zen2** [custom-cards/bar-card#100]
I suppose that like me a lot of users create a gradient using from/to/color list in severity options.
It will be really cool to do not calculate the gradient and make the list manually and to have an option to calculate the gradient.
That could be represented like this:

```
severity:
  - from: -5
    color-from: blue
    to: 24
    color-to: green
    color-step: 1
  - from: 24
    color-from: green
    to: 40
    color-to: red
    color-step: 1
```

Note: [How to calculate gradient values](https://stackoverflow.com/questions/22218140/calculate-the-color-at-a-given-point-on-a-gradient-between-two-colors)
