### ISSUE TITLE
"decimal" not used for "complementary" bar

### ISSUE THREAD

**Issue by ildar170975** [custom-cards/bar-card#108]
Seems that "decimal" property doesn't affect if "complementary: true".
For 2 bars same "decimal: 3" property is specified.

```
type: 'custom:bar-card'
entities:
  - entity: sensor.memory_use_percent
    name: Free RAM (complementary)
    complementary: true
    decimal: '3'
    color: green
  - entity: sensor.memory_use_percent
    name: Used RAM
    complementary: false
    decimal: '3'
    color: red
```
![изображение](https://user-images.githubusercontent.com/71872483/96518966-a3e2fb00-1274-11eb-8003-004dc589bcf2.png)
