### ISSUE TITLE
Complementary value with many digits after decimal point

### ISSUE THREAD

**Issue by ildar170975** [custom-cards/bar-card#109]
Sometimes a glitch occurs - many digits after decimal point for complementary value.
Usually it occurs if limits (min, max) are specified:

```
type: 'custom:bar-card'
entities:
  - entity: sensor.memory_use_percent
    name: Free RAM (0..80)
    complementary: true
    decimal: '3'
    color: green
    limit_value: true
    min: '0'
    max: '80'
  - entity: sensor.memory_use_percent
    name: Used RAM
    complementary: false
    decimal: '3'
    color: red
```

![изображение](https://user-images.githubusercontent.com/71872483/96519415-a1cd6c00-1275-11eb-97f3-2ff15e782f95.png)
