### ISSUE TITLE
Clarifications for "limit_value" required - seems that "limiting" always happens

### ISSUE THREAD

**Issue by ildar170975** [custom-cards/bar-card#110]
As it was specified for "limit_value" property:
![изображение](https://user-images.githubusercontent.com/71872483/96519899-a6deeb00-1276-11eb-95c5-2554a4036e47.png)

But it looks that "limiting" happens always independently on the "limit_value" property:

```
type: 'custom:bar-card'
entities:
  - entity: sensor.memory_use_percent
    name: 'Free RAM (0..100, limit_value=false)'
    complementary: true
    limit_value: false
    min: '0'
    max: '100'
    color: green
  - entity: sensor.memory_use_percent
    name: 'Used RAM (0..100, limit_value=true)'
    complementary: false
    limit_value: true
    min: '0'
    max: '100'
    color: red
  - entity: sensor.memory_use_percent
    name: 'Free RAM (0..80, limit_value=false)'
    complementary: true
    limit_value: false
    min: '0'
    max: '80'
    color: green
  - entity: sensor.memory_use_percent
    name: 'Used RAM (30..80, limit_value=true)'
    complementary: false
    limit_value: true
    min: '30'
    max: '80'
    color: red
```
![изображение](https://user-images.githubusercontent.com/71872483/96520205-40a69800-1277-11eb-928c-b901989a9329.png)
