### ISSUE TITLE
[Feature Request] hide if unavailable

### ISSUE THREAD

**Issue by amitkeret** [custom-cards/bar-card#121]
I think it would be useful to have an option to hide a bar if the entity is unavailable.
Something similar to the implementation in [multiple-entity-row](https://github.com/benct/lovelace-multiple-entity-row#entity-objects)

**Use case**
Using this card inside a [decluttering-card](https://github.com/custom-cards/decluttering-card), this card needs to be able to accept an unknown number of entities.

**Example expected behaviour**
If the decluttering template allows for 5 bars, but only 3 entities are passed to it, it will render 3 bars.

**Current behaviour**
5 bars are rendered, with the last 2 showing "Entity not available" errors.

**Comment by amitkeret** [comment]
I've managed to come up with a workaround:
Creating a helper entity input_number.dummy_number, which instantiates with a value of 0.
Then I defined this entity as the default entity in a `decluttering-card` template.
Using the zero-value, I can use a severity threshold to hide the graph.

```yaml
decluttering_templates:
  bars_test:
    default:
      - bar2: input_number.dummy_number
      - bar3: input_number.dummy_number
    card:
      type: 'custom:bar-card'
      entities:
        - entity: '[[bar1]]'
        - entity: '[[bar2]]'
          severity:
            - from: 0
              to: 0
              hide: true
        - entity: '[[bar3]]'
          severity:
            - from: 0
              to: 0
              hide: true

cards:
  - type: 'custom:decluttering-card'
    template: bars_test
    variables:
      - bar1: sensor.temperature1
      - bar2: sensor.temperature2
      - bar3: sensor.temperature3

  # The following will render just one bar
  - type: 'custom:decluttering-card'
    template: bars_test
    variables:
      - bar1: sensor.temperature1
```

This is obviously a convoluted workaround...
Native support would be nice. See again `multiple-entity-row`.
