### ISSUE TITLE
Severity level for non-numeric values & Display text for values

### ISSUE THREAD

**Issue by Tom-ahawk** [custom-cards/bar-card#130]
For my example I have a sensor with air quality values (attributes), one of the attributes is the sum index for all measured values in string (low, medium, high, severe) and another sensor with with states like: low/medium/hight/severer.

1. Enhance existing severity option code to change displayed value to displayed text, this way an explanatory text can be displayed instead of value:

```
entity: sensor.example
title: Severity
type: 'custom:bar-card'
severity:
  - color: Green
    display: "Low"
    from: 0
    to: 25
  - color: Orange
    display: "High"
    from: 26
    to: 50
  - color: Red
    display: "Severe"
    from: 51
    to: 100
```

2. Please consider making the severity option for non-numeric values (and the %-range they apply up to,  on the bar) like:

         severity:
           - color: green
             display: "low" #if display is not used then use the sensors state/attribute text
             from%: 0
           - color: orange
             display: "medium"
             from%: 40
           - color: red
             display: "hight"
             from%: 80
           - color: purple 
             display: "severe"
             from%: 90

![image](https://user-images.githubusercontent.com/35527507/138088933-589cdf27-5716-4635-8731-3c0f7216a1b4.png)

Today (6/7) the standard Gauge Card got "label string" (optional), - Label of the segment. This will be shown instead of the value.
Hope the bar-card gets it to.
