### ISSUE TITLE
Rounded corners

### ISSUE THREAD

**Issue by lcavalli** [custom-cards/bar-card#137]
It would be nice to have the possibility to apply rounded corners to the bar. Not sure it can be achieved with alternative methods, like card-mod.

**Comment by lcavalli** [comment]
Looking at this screenshot
![image](https://user-images.githubusercontent.com/6123641/154809625-81dea841-4cc1-4e5d-a746-b39a66a74cc4.png)
it is possible, but the sample code presented
```yaml
entity: sensor.example
positions:
  icon: 'off'
  indicator: inside
  name: outside
type: 'custom:bar-card'
width: 70%
title: 2.0.0 Default Layout
style: |-
  bar-card-value {
    margin-right: auto;
    font-size: 13px;
    font-weight: bold;
    text-shadow: 1px 1px #0005;
  }
```
doesn't produce the same result.

**Comment by lcavalli** [comment]
Solved, this is the correct style to apply:
```yaml
style: |-
  bar-card-currentbar, bar-card-backgroundbar {
    border-radius: 4px;
  }
```

**Comment by bcutter** [comment]
So why did you close this issue? I was running into the same and searching my back off why the example is not working.

You fixed it for you (and I'm thankful for sharing your solution), but the docs at https://github.com/custom-cards/bar-card#200-default-layout-requires-card-mod are still wrong.

So just REOPEN and FIX the docs ⚠

**Comment by killtux** [comment]
for me both (docs and this example are not working). it also reformats it in following style. what could be the problem?

```
type: custom:bar-card
entities:
  - entity: sensor.tesla_battery_level
style: |-
  bar-card-currentbar, bar-card-backgroundbar {
    border-radius: 4px;
  }

```

**Comment by ildar170975** [comment]
> for me both (docs and this example are not working). it also reformats it in following style. what could be the problem?

The example is a bit outdated, check card-mod Docs for a proper syntax. In short - a "card_mod" keyword is missing.

**Comment by killtux** [comment]
> > for me both (docs and this example are not working). it also reformats it in following style. what could be the problem?
> 
> The example is a bit outdated, check card-mod Docs for a proper syntax. In short - a "card_mod" keyword is missing.

ahhh thx for the hint. if anyone is also searching for it here's the complete code:

```
type: custom:bar-card
entities:
  - entity: sensor.tesla_battery_level
card_mod:
  style: |-
    bar-card-currentbar, bar-card-backgroundbar {
      border-radius: 10px;
    }

```

**Comment by ghost** [comment]
This isn't working for me.


> ahhh thx for the hint. if anyone is also searching for it here's the complete code:
> 
> ```
> type: custom:bar-card
> entities:
>   - entity: sensor.tesla_battery_level
> card_mod:
>   style: |-
>     bar-card-currentbar, bar-card-backgroundbar {
>       border-radius: 10px;
>     }
> ```

HAOS latest updates 2025.9.1 - I have  card-mod installed via HACS.  My code:

```
entities:
  - entity: sensor.van_battery_battery
    name: battery
    severity:
      - color: Red
        from: 0
        to: 10
      - color: Orange
        from: 11
        to: 33
      - color: limegreen
        from: 34
        to: 100
    icon: mdi:battery

card_mod:
  style: |-
    bar-card-currentbar, bar-card-backgroundbar {
      border-radius: 30px;
    }
    
animation: "on"
decimal: none
positions:
  icon: inside
  title: outside
direction: up
height: 200px
width: 100%
stack: horizontal
type: custom:bar-card
grid_options:
  columns: 12
  rows: auto

```
