### ISSUE TITLE
attribute field also change the bar level

### ISSUE THREAD

**Issue by roumano** [custom-cards/bar-card#149]
On the documentation the **attribute field** is used for `Displays a specific attribute instead of state value.`

But when using it, it's also change the bar level to the value of the attribute field

This issue issue and with the issue #124 , where the value is never refreshed, i'm blocked to do what i want with the custom-card

My origin variable is not between 0 and 100 and i want to use a dynamic max value

as example i have created this variable : 
```
circuit_a_percentage:
  state: 16.9
  conso: 36.4
```
I want to use bar-card with level of `16.9%` and display `36.4`

And with the original variable and `custom:config-template-card` i use like this : 
```
type: custom:config-template-card
variables:
  max_containers: states['sensor.phase_a_power'].state
entities:
  - ${max_containers}
card:
  type: custom:bar-card
  entity: sensor.circuit_1_power
  name: '1 - Ligne A '
  max: ${max_containers}
```
It's working but the data on bar-card is never refresh (only when i edit the card )
