### ISSUE TITLE
Severity values with entities

### ISSUE THREAD

**Issue by PeteCondliffe** [custom-cards/bar-card#15]
Is there any way to use basic operations in severity or am I missing something

```
  - type: custom:bar-card
    entity: sensor.devices_online
    min: 0
    max: sensor.total_devices
    severity:
      - value: sensor.total_devices
        color: var(--primary-color)
      - value: sensor.devices_online
        color: orange
```

`sensor.total_devices` is relatively static and `sensor.devices_online` will always be less than or equal to `sensor.total_devices` I don't see a way I can ever trigger the second severity without something like 
`- value: sensor.total_devices -1`
or the ability for a greater than operation.

I hope this makes sense and i'm missing something simple
Thanks
