### ISSUE TITLE
Weird border around a bar-card after 2022.11

### ISSUE THREAD

**Issue by ildar170975** [custom-cards/bar-card#152]
A border is displayed around a bar-card placed inside Entities card after 2022.11:

![изображение](https://user-images.githubusercontent.com/71872483/200124200-d51cfb99-f39e-490f-88df-04a21fc31003.png)

```
type: entities
entities:
  - type: custom:bar-card
    entity: sensor.processor_use
    entity_row: true
  - type: custom:bar-card
    entity: sensor.processor_use
    entity_row: false
```
This border also conflicts with a default radius for the bar-card:
![изображение](https://user-images.githubusercontent.com/71872483/200128368-dc78c657-11b2-4db6-8348-17a52e210d33.png)
since the `--ha-card-border-radius` var is undefined by default.

**Proposal - do not show a border at all.**

------------------

Meanwhile this may be fixed by card-mod:
```
    type: entities
    title: Removing a border
    entities:
      - type: custom:bar-card
        title: default
        entity: sensor.memory_use_percent
      - type: custom:bar-card
        title: card-mod
        entity: sensor.memory_use_percent
        card_mod:
          style: |
            ha-card {
              --ha-card-border-width: 0px;
            }
```
![изображение](https://user-images.githubusercontent.com/71872483/200128721-9f82388a-78fa-4ffa-a63f-278d47240d7a.png)
