### ISSUE TITLE
Cannot change style of title

### ISSUE THREAD

**Issue by woobenjamin** [custom-cards/bar-card#162]
All, I've tried (at least what I think) is every iteration of trying to change the style of the title with no success!
**What I'm trying to do**
Change the look of the title (card-header)
**What I've tried**
I know that I have to do something with the styling, but no matter what I try (please see my config after the picture), it won't change the styling
The only thing that works is if I define ```--ha-card-header-font-size: 12px;``` but that only changes the font size, and I want to do quite a bit more to the title. 

![image](https://user-images.githubusercontent.com/45885373/233459420-d4b3e61e-8a34-48cb-a9dc-c1b2a90f26df.png)

```
type: custom:bar-card
title: Brother MFC-L6540DW
... removed to save space ...
entities:
  - entity: sensor.brother_mfc_j6540dw_c
    name: C
    color: cyan
... removed to save space ...
style: |-
  .card-header {
    font-size: 12px;
  }
  bar-card-card {
    margin: 0px;
    border-radius: 12px;
  }
  bar-card-name {
    font-size: 14px;
    font-weight: normal;
  }
  bar-card-value {
    font-size: 12px;
    font-weight: bold;
  }
```
I've also tried:
```
card_mod:
  style: |
    .card-header {
      font-size: 12px;
      font-weight: bold;
    }
```

Thanks in advance!

ben

**Comment by alexruffell** [comment]
Have you found a solution? I have your same issue... the title doesn't change even though the styling should make it smaller.

<img width="393" alt="image" src="https://github.com/custom-cards/bar-card/assets/4006944/4f5b8b30-b81a-4ed5-a17f-0f135aeeb0cd">


```
type: custom:bar-card
card_mod:
  style: |
    .card-header {
      font-size: 18px;
      padding: 2px 15px 2px 15px
    }
entities:
  - entity: sensor.hp_color_laserjet_mfp_m277dw_black_cartridge_hp_cf400x
    direction: right
    color: Black
    width: 86%
    height: 25px
    name: CF400X
  - entity: sensor.hp_color_laserjet_mfp_m277dw_cyan_cartridge_hp_cf401x
    direction: right
    color: Cyan
    width: 86%
    height: 25px
    name: CF401X
  - entity: sensor.hp_color_laserjet_mfp_m277dw_yellow_cartridge_hp_cf402x
    direction: right
    color: Yellow
    width: 86%
    height: 25px
    name: CF402X
  - entity: sensor.hp_color_laserjet_mfp_m277dw_magenta_cartridge_hp_cf403x
    direction: right
    color: Magenta
    width: 86%
    height: 25px
    name: CF403X
max: '100'
min: '0'
unit_of_measurement: '%'
stack: vertical
title: Printer Toner Levels
positions:
  value: inside
  name: outside
  indicator: 'off'
  minmax: 'off'
  icon: 'off'
```
