### ISSUE TITLE
Feature Request:  Auto-Hide bar-card entities with 0.0 value

### ISSUE THREAD

**Issue by mkanet** [custom-cards/bar-card#166]
I tried various different ways to automatically hide each bar when their value/state = '0.0'.  None of them work correctly.  I exhausted all possibilities (templating, state_filter, and entity-filter)

Could you please suggest a way to do this or please add this feature?  I looked in the documentation, I couldn't find any way to do this.

Thank you in advance.

**Comment by xZetsubou** [comment]
Use severity option
```yaml
title: Synology
type: custom:bar-card
severity:
  - hide: true
    from: 0
    to: 0
entities:
  - entity: sensor.syno_cpu_load_average_15_min
```
