### ISSUE TITLE
[FR] Hide the card if all bars are hidden

### ISSUE THREAD

**Issue by ildar170975** [custom-cards/bar-card#167]
Consider this card:
```
  - type: custom:bar-card
    severity:
      - from: '0'
        to: '0'
        hide: true
      - from: '1'
        to: '40'
        color: '#007A00'
      - from: '41'
        to: '90'
        color: '#EA9000'
      - from: '91'
        to: '100'
        color: '#C41400'
    entities:
      - entity: input_number.test_level_1
```
![image](https://github.com/custom-cards/bar-card/assets/71872483/bd17ef68-88b6-47cf-b475-45ab3beb2ec1)

When a bar is hidden - the card still is displayed:

![image](https://github.com/custom-cards/bar-card/assets/71872483/5922fef7-2be7-4301-a56f-f5a810b9392d)

This may be solved by card-mod, but I would like to suggest an option: when it is set to `true`:
-- if no bars are displayed - hide the whole card.
