### ISSUE TITLE
Hide when unavailable

### ISSUE THREAD

**Issue by Markyt77** [custom-cards/bar-card#183]
Building on issue #60 would it be possible to expand this so that I can hide individual bars when the sensor becomes 'unavailable' or 'unknown'?  I tried with card-mod/css ({% if states("sensor.altherma_climatecontrol_leaving_water_temperature") in ['unavailable','unknown'] %}) but couldn't get that it work

**Comment by jopocop** [comment]
I have a bar with a scale of 0...100 (%). I created a template sensor that is equals to the real entity value, except in situations I want to hide the bar, I'll just force the template sensor to be 101. And in frontend I use the following colorcoding. 
```
              severity:
                - color: Red
                  from: 0
                  to: 50
                - color: Green
                  from: 51
                  to: 100
                - color: Black
                  from: 101
                  to: 102
                  hide: true
```
However, this just broke. I did upgrade to the latest HA Core, but have no idea if that is related to this error. In any case the hide: true does not work any more.
Edit: It works, but only after page refresh.
Edit2: card-templater was the reason. Bar-chart can't hide/unhide if within card-templater. --> Solved.
