### ISSUE TITLE
Actions 2024.8 not supported

### ISSUE THREAD

**Issue by ildar170975** [custom-cards/bar-card#189]
In 2024.8 some changes were made for action.
Consider this code:
```
  - type: custom:bar-card
    entity: sensor.system_monitor_disk_free
    tap_action:
      action: perform-action
      perform_action: input_boolean.toggle
      target:
        entity_id: input_boolean.test_boolean

  - type: custom:bar-card
    entity: sensor.system_monitor_disk_free
    tap_action:
      action: call-service
      service: input_boolean.toggle
      service_data:
        entity_id: input_boolean.test_boolean
```
![Image](https://github.com/user-attachments/assets/7a2e0dab-5f60-4c7b-9f64-783d594b36be)

Only the 2nd syntax (legacy) works.

**Comment by clau-bucur** [comment]
This new-style code does not work either:
```
- type: custom:bar-card
  entities:
    - entity: sensor.nuc_cpu_usage
      name: CPU usage
      tap_action:
        action: more-info
        entity: sensor.average_usage_cpu_nuc
```

**Comment by imdeepjee** [comment]
Did you find a way to make it work?
I'm having the same issue

**Comment by ildar170975** [comment]
You may still use old syntax.

**Comment by xstrex** [comment]
Came here to open this issue; thank you. 
This worked for me:
```yaml
tap_action:
  action: call-service
  service: input_number.set_value
  service_data:
    entity_id: input_number.humidifier_on
    value: "0"
```
