### ISSUE TITLE
icon versus entity_picture

### ISSUE THREAD

**Issue by netsoft-ruidias** [custom-cards/bar-card#194]
Some entities in the Home Assistant have the `entity_picture` property that allows us to replace the icon with an image.
For example, the entities of the "person" domain but there are other examples.

The "tile" card already supports this feature from scratch, where it is possible to display an image instead of the entity's icon, without any effort.
Example:
```yaml
type: tile
entity: person.xxx_xxxx
vertical: false
show_entity_picture: true
```

It would be interesting and extremely useful if the `bar-card` also had the possibility to display an image instead of an entity icon.
