### ISSUE TITLE
Because Repository is no longer maintained, custom-cards/bar-card has been removed from HACS. Please help me solve the problem.

### ISSUE THREAD

**Issue by VikeDragon** [custom-cards/bar-card#199]
Core
2025.6.1
Supervisor
2025.05.5
Operating System
15.2

Got message :

Because Repository is no longer maintained, custom-cards/bar-card has been removed from HACS. Please visit the [HACS Panel](https://***) to remove it.

Please help me solve the problem. This is a great interface ui card, I don't want to lose it.

**Comment by dengi76** [comment]
Hello. I have the same thing!?!

**Comment by obhatti87** [comment]
Got the same message this morning

**Comment by chrisgilldc** [comment]
Same. I don't have the knowledge to get this back into shape but find it very useful.

**Comment by nilsreiter** [comment]
Well, unless someone takes over the maintenance of the bar-card, this issue will not go away. Depending on your use case, https://github.com/francois-le-ko4la/lovelace-entity-progress-card might be an alternative.

**Comment by CrallH** [comment]
Add a forked as custom that is updated, this one for example: https://github.com/spacerokk/bar-card

**Comment by liuk4friends** [comment]
> Add a forked as custom that is updated, this one for example: https://github.com/spacerokk/bar-card

What is the procedure to replace the no longer updated version with the forked one that is still maintained?

**Comment by tomlut** [comment]
> What is the procedure

Uninstall original bar card from HACS.
Add custom repository to HACS (https://github.com/spacerokk/bar-card)
Install forked bar card in HACS.

Or just ignore the warning because the original card still works where as the fork does not.

**Comment by xbmcnut** [comment]
Switched to [https://github.com/spacerokk/bar-card](https://github.com/spacerokk/bar-card) just now after uninstalling original and it seems to work just fine.

**Comment by tomlut** [comment]
Two out of every three of my cards failed to display correctly. Probably because of a config options change but I have yet to work out what it is. Or bother working out what it is as the bar card still works. 

![Image](https://github.com/user-attachments/assets/bf2c3473-f8c6-4d5d-a5f8-78ccd72aea63)

![Image](https://github.com/user-attachments/assets/89877cf1-f8cf-404a-a380-231e4993d833)

![Image](https://github.com/user-attachments/assets/d9b900a0-1e98-4ae3-a9dd-fd152e9b0684)

![Image](https://github.com/user-attachments/assets/d94ee78f-ee2a-4671-bf56-dcc3f6c52437)

**Comment by xbmcnut** [comment]
@tomlut Oooh, any chance you could share your card code for the Energy and Power? Looks very nice 🤗

**Comment by tomlut** [comment]
```
entities:
  - entity: sensor.energy_tariff_in_use
  - direction: right
    entities:
      - entity: sensor.self_solar
        name: Power From Solar
      - entity: sensor.export
        name: Power To Grid
    entity_row: true
    height: 28px
    max: 6000
    min: 0
    positions:
      icon: inside
      indicator: "off"
      title: "off"
    severity:
      - color: "#039BE5"
        from: -1
        to: 300
      - color: "#e0b400"
        from: 300.1
        to: 900
      - color: "#0da035"
        from: 900.1
        to: 7000
    type: custom:bar-card
    value_style:
      color: var(--primary-text-color)
      text-shadow: none
    card_mod:
      class: inline-card-no-border
  - direction: right
    entities:
      - entity: sensor.import
        name: Power From Grid
    entity_row: true
    height: 28px
    max: 6000
    min: 0
    positions:
      icon: inside
      indicator: "off"
      title: "off"
    severity:
      - color: "#039BE5"
        from: -1
        to: 300
      - color: "#0da035"
        from: 300.1
        to: 900
      - color: "#e0b400"
        from: 900.1
        to: 1800
      - color: "#e45e65"
        from: 1800.1
        to: 7000
    type: custom:bar-card
    value_style:
      color: var(--primary-text-color)
      text-shadow: none
    card_mod:
      class: inline-card-no-border
  - direction: right
    entities:
      - entity: sensor.total_cost_today
      - entity: sensor.total_cost_24hrs_ago
      - entity: sensor.predicted_cost_today
    entity_row: true
    height: 28px
    max: 10
    min: -3
    target: "0"
    positions:
      icon: inside
      indicator: "off"
      title: "off"
    severity:
      - color: "#039BE5"
        from: -5
        to: 1.49
      - color: "#0da035"
        from: 1.5
        to: 2.99
      - color: "#e0b400"
        from: 3
        to: 4.49
      - color: "#e45e65"
        from: 4.5
        to: 10
    type: custom:bar-card
    value_style:
      color: var(--primary-text-color)
      text-shadow: none
    card_mod:
      class: inline-card-no-border
  - direction: right
    entities:
      - entity: sensor.next_bill_estimate
    entity_row: true
    height: 28px
    max: 250
    min: -50
    positions:
      icon: inside
      indicator: "off"
      title: "off"
    severity:
      - color: "#039BE5"
        from: -200
        to: 49.99
      - color: "#0da035"
        from: 50
        to: 99.99
      - color: "#e0b400"
        from: 100
        to: 149.99
      - color: "#e45e65"
        from: 150
        to: 1000
    type: custom:bar-card
    value_style:
      color: var(--primary-text-color)
    card_mod:
      class: inline-card-no-border
show_header_toggle: false
title: Energy and Power
type: entities
state_color: true
card_mod:
  class: top-level-card
```

**Comment by donparlor** [comment]
I'm also a heavy user of that repository, I'm jumping in to show my interest to see that repository maintained if anyone has the skills to do so:

<img width="505" alt="Image" src="https://github.com/user-attachments/assets/548be77f-ca2d-4cd6-b3da-c3773103fbae" />

**Comment by 0000Max0000** [comment]
> Add a forked as custom that is updated, this one for example: https://github.com/spacerokk/bar-card

I receive the following error :

![Image](https://github.com/user-attachments/assets/5059c73a-7bb3-4f84-93f3-3d7cf55dbf26)

**Comment by Mosher23** [comment]
> > Add a forked as custom that is updated, this one for example: https://github.com/spacerokk/bar-card
> 
> I receive the following error :
> 
> ![Image](https://github.com/user-attachments/assets/5059c73a-7bb3-4f84-93f3-3d7cf55dbf26)

It should be [ spacerokk/bar-card](url) without https://Github.com

**Comment by danVnest** [comment]
I just migrated to https://github.com/spacerokk/bar-card
(@0000Max0000 use the type `Dashboard` instead of `Integration`)

All seems to be working ([card code here](https://github.com/danVnest/home-assistant/blob/05d9fcdc0977b7e40e260ca39d354202309d27ee/.storage/lovelace#L2510)):
<img src="https://github.com/user-attachments/assets/9eccba1f-aa73-45c9-8db7-ba720dcc2a02" width="300">

**Comment by WhimsySpoon** [comment]
I've just migrated to [spacerokk/bar-card](https://github.com/spacerokk/bar-card).

The only issues I had involved integers being written as strings in the config (`"100"` instead of `100`). The previous version seemed to tolerate this, but the new one does not - and rightly so!

Once I looked through the yaml and found all instances and corrected them by removing the quotes, everything worked perfectly.

**Comment by xbmcnut** [comment]
> > > Add a forked as custom that is updated, this one for example: https://github.com/spacerokk/bar-card
> > 
> > 
> > I receive the following error :

> 
> It should be [ spacerokk/bar-card](url) without https://Github.com

It's a 'Dashboard' not an 'Integration'

**Comment by donparlor** [comment]
@xbmcnut Will this repo be kept up-to-date by spacerokk ??
https://github.com/spacerokk/bar-card

For now I simply clicked on ignore in my system but I would like to have a stable card for the future.

**Comment by CrallH** [comment]
> [@xbmcnut](https://github.com/xbmcnut) Will this repo be kept up-to-date by spacerokk ?? https://github.com/spacerokk/bar-card
> 
> For now I simply clicked on ignore in my system but I would like to have a stable card for the future.

Not a single update for 5 year's 😄 don't think it will....

**Comment by donparlor** [comment]
@CrallH, ok, I thought the spacerokk version was maintained. If anyone can lead with the required changes, that would be great

**Comment by tomlut** [comment]
> I thought the spacerokk version was maintained.

It is. The last update was three weeks ago. CrallH is incorrect. 

![Image](https://github.com/user-attachments/assets/02f87fcc-6c44-4e7f-9ace-4593be926103)

**Comment by dan-s-github** [comment]
I also migrated to the [spacerokk](https://github.com/spacerokk/bar-card) fork but have an issue with the entity name on the card

![Image](https://github.com/user-attachments/assets/1690a0a9-b8b2-4f3f-b272-526e81ca95b2)

before the 'name_attr' was actually evaluated

```
    entities:
      - entity: sensor.weatherflow_forecast_0
        name_attr: time
      - entity: sensor.weatherflow_forecast_1
        name_attr: time
      - entity: sensor.weatherflow_forecast_2
        name_attr: time
      - entity: sensor.weatherflow_forecast_3
        name_attr: time
      - entity: sensor.weatherflow_forecast_4
        name_attr: time
      - entity: sensor.weatherflow_forecast_5
        name_attr: time
      - entity: sensor.weatherflow_forecast_6
        name_attr: time
      - entity: sensor.weatherflow_forecast_7
        name_attr: time
```

anyone know how to fix this?

**Comment by tomlut** [comment]
Report it as an issue in the other repository. The dev isn't going to look here.

**Comment by dan-s-github** [comment]
Unfortunately the way the repo was forked does not allow to create issues there. At least I couldn't find where to create issues on the forked repo

**Comment by CrallH** [comment]
> > I thought the spacerokk version was maintained.
> 
> It is. The last update was three weeks ago. CrallH is incorrect.
> 
> ![Image](https://github.com/user-attachments/assets/02f87fcc-6c44-4e7f-9ace-4593be926103)

Yes, a misunderstanding from my part, I thought he ment this repo 👍

**Comment by craigmcfly** [comment]
> Switched to https://github.com/spacerokk/bar-card just now after uninstalling original and it seems to work just fine.

+1 to this. Couple of bugs that I'm sure they'll sort in due time, but otherwise it's great to see the code being maintained!

**Comment by dan-s-github** [comment]
Fixed my issue by using the `custom:config-template-card`

![Image](https://github.com/user-attachments/assets/f327fbe5-4fc7-47c7-92cd-35bb73d8eb69)

Posting here in case someone else faces a similar issue.

```
   ...              
   - type: custom:config-template-card
      entities:
        - sensor.weatherflow_forecast_0
        - sensor.weatherflow_forecast_1
        - sensor.weatherflow_forecast_2
        - sensor.weatherflow_forecast_3
        - sensor.weatherflow_forecast_4
        - sensor.weatherflow_forecast_5
        - sensor.weatherflow_forecast_6
        - sensor.weatherflow_forecast_7
      card:
         type: custom:bar-card
         ....
         entities:
            - entity: sensor.weatherflow_forecast_0
              name: >-
                ${states['sensor.weatherflow_forecast_0'].attributes.time}
            - entity: sensor.weatherflow_forecast_1
              name: >-
                ${states['sensor.weatherflow_forecast_1'].attributes.time}
            - entity: sensor.weatherflow_forecast_2
              name: >-
                ${states['sensor.weatherflow_forecast_2'].attributes.time}
            - entity: sensor.weatherflow_forecast_3
              name: >-
                ${states['sensor.weatherflow_forecast_3'].attributes.time}
            - entity: sensor.weatherflow_forecast_4
              name: >-
                ${states['sensor.weatherflow_forecast_4'].attributes.time}
            - entity: sensor.weatherflow_forecast_5
              name: >-
                ${states['sensor.weatherflow_forecast_5'].attributes.time}
            - entity: sensor.weatherflow_forecast_6
              name: >-
                ${states['sensor.weatherflow_forecast_6'].attributes.time}
            - entity: sensor.weatherflow_forecast_7
              name: >-
                ${states['sensor.weatherflow_forecast_7'].attributes.time}

```
