### ISSUE TITLE
Bar becomes invisible when severity is defined

### ISSUE THREAD

**Issue by lancer73** [custom-cards/bar-card#24]
The bar becomes invisible when the severity is defined, but not always. 

e.g. only shows the temperature and title in the card. Remove the severity and the bar shows. No errors in the javascript console.

type: 'custom:bar-card'
title: Tapwater
show_icon: true
entity: sensor.heatpump_tapgemeten
min: 35
max: 65
target: 58
severity:
  - value: 40
    color: '#bf4040'
  - value: 50
    color: '#bf9540'
  - value: 55
    color: '#40bf40'

**Comment by chhofi** [comment]
I can confirm this error.

**Comment by demidovskiy** [comment]
This problem is related if you have a value of "10.0" that is, "instead of". ", If the value was" 10.0 "then the graph was drawn correctly

**Comment by LintHart** [comment]
Following, also seeing this error

**Comment by Gluwc** [comment]
> This problem is related if you have a value of "10.0" that is, "instead of". ", If the value was" 10.0 "then the graph was drawn correctly

I'm a bit unclear what you mean by this. Could you give me some more info?

**Comment by gdude2002** [comment]
I can also confirm this issue, but it appears to work if you used named CSS colours.

```yaml
- entity: sensor.192ky513_fuel_level
  severity:
    - value: 0
      color: '#b92929'
    - value: 40
      color: '#b7b929'
    - value: 75
      color: '#039be5'
  color: '#b92929'
  unit_of_measurement: '%'
  min: 0
  max: 100
  type: 'custom:bar-card'
```

**Comment by gdude2002** [comment]
Ah, okay, I figured it out. You need to build your severities from the upper value, rather than the lower value.

```yaml
- entity: sensor.192ky513_fuel_level
  severity:
    - value: 30
      color: '#b92929'
    - value: 65
      color: '#b7b929'
    - value: 100
      color: '#039be5'
  color: '#B92929'
  unit_of_measurement: '%'
  min: 0
  max: 100
  type: 'custom:bar-card'
```
