### ISSUE TITLE
Can not set options for entities in a list?

### ISSUE THREAD

**Issue by fribse** [custom-cards/bar-card#26]
custom:bar-card v 1.6.2

Not sure if I read the documentation right.

entities | array | none | A list of entities. Accepts individual config options per defined entity.

As I read it, I can add
```
entities:
  - a
  - b
  - c
```

and give config options for each of them, but I get an error about bad indentation when doing so.

I would like to set the bars of each of them to have specific colous.

**Comment by Gluwc** [comment]
This probably isn't documented well, but here's how it supposed to work.

```
      - entities:
          - entity: sensor.version_local
            title: Local Version
          - entity: sensor.version_docker
            title: Docker Version
```

I'll see if I can add a better example to the docs when I have some time.
