### ISSUE TITLE
Bar size scaled after the largest number?

### ISSUE THREAD

**Issue by fribse** [custom-cards/bar-card#35]
Hi there

HA: 0.106.3
Bar-graph: 1.7.1
auto-entities: 16

I've just installed the Corona sensor here, and made a card like this:

```
  - card:
      max: 100000
      min: 0
      padding: 2px
      title_position: inside
      type: 'custom:bar-card'
    filter:
      include:
        - entity_id: '*worldwide_coronavirus*'
    sort: entity_id
    type: 'custom:auto-entities'
```

As you can see I've set the max to 100.000, which I then have to adjust when we cross that thresshold.
Is it possible to have just the largest number determine the length of the bar, and have the others scaled down to size?
