### ISSUE TITLE
Round border bar

### ISSUE THREAD

**Issue by mcasper73** [custom-cards/bar-card#40]
Hy, today i converted gauge card to bar card. It is very beautiful job your card, thank you.
how can I have the round edge of the bar like you example ?
I use normally car-mod to round border of other cards.
I try with code behind but dont' work.
card_style: 
     border-radius: 10px

I use v. 3.0.1 and i have restarted.
- type: 'custom:bar-card'
  entity: sensor.processor_use
  card_style: 
    border-radius: 10px
  severity:
    - color: green
      from: 0
      to: 50
    - color: orange
      from: 51
      to: 75
    - color: red
      from: 76
      to: 100

Thank you for you efforts.

**Comment by Gluwc** [comment]
The border radius can be set in a theme using `bar-card-border-radius` and defaults to `ha-card-border-radius`. However `ha-card-border-radius` also changes the border radius of all HA cards.

```yaml
example:

  # Using ha-card-border-radius.
  ha-card-border-radius: '8px'

  # Using bar-card-border-radius.
  bar-card-border-radius: '8px'
```
The `card_style` config option is no longer used, instead you'll have to use [card-mod](https://github.com/thomasloven/lovelace-card-mod) if you want to set it specifically per card.

```yaml
entity: sensor.example
title: Default
type: 'custom:bar-card'
style: |-
  bar-card-current, bar-card-backgroundbar {
    border-radius: 8px;
  }
```
