### ISSUE TITLE
stack:vertical

### ISSUE THREAD

**Issue by jschafermo** [custom-cards/bar-card#41]
Good afternoon, appreciate the bar card!  

I would like to stack:vertical two entities such as Watts and Amps.  I'm able to stack these two sensors, but would like to change the severity of the two sensors.  I can define the severity for the sensors as a ground, but not individually.  Is it possible to define the severity of individual sensor when stack:vertical is used?

Thanks

**Comment by Gluwc** [comment]
You can define every card config on every individual entry in the entities array regardless of the `stack` option:

```yaml
entities:
  - entity: sensor.example
    severity:
      - from: 0
        to: 10
        color: Red
      - from: 11
        to: 20
        color: Orange
      - from: 30
        to: 40
        color: Green
  - entity: sensor.example
    severity:
      - from: 0
        to: 10
        color: Purple
      - from: 11
        to: 20
        color: Blue
      - from: 30
        to: 40
        color: Cyan
  - entity: sensor.example
title: Multiple Severity
type: 'custom:bar-card'
```
Also the default stacking is already set to `stack: vertical` so you don't have to define this, unless you meant `stack: horizontal`.
