### ISSUE TITLE
Having Title inside keeping it in the default position

### ISSUE THREAD

**Issue by Shaun-Harrison** [custom-cards/bar-card#42]
Hello

I've got the following code and expecting the title to be inside the bar chart

` - type: custom:bar-card

    entity: sensor.time_shaun_been_home

    title: Time Spent Home

    align: split

    color: 'var(--primary-color)'

    positions:

      icon: 'off'

      title: 'inside'`

![image](https://user-images.githubusercontent.com/46562010/78545470-bd01ee00-77f3-11ea-9235-10a63c611db9.png)

But as you can see in the screenshot the title is staying in the default position as well as being inside

**Comment by Gluwc** [comment]
I'm not sure what you are expeciting to happen? The default for the title position is already `inside` so this won't change anything. 
You can change it to `outside` to move it out of the bar.

**Comment by Gluwc** [comment]
If you want to keep the title position the same but not show the icon you'll have to do some CSS to hide the icon instead.

```yaml
entity: sensor.example
name: Bar Card
type: 'custom:bar-card'
style: |-
  ha-icon {
    visibility: hidden;
  }
```
