### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by PierreScerri** [custom-cards/bar-card#47]
Hi

In version 2 I had the following setup:

[Screen Recording 2020-04-09 at 13.29.59.zip](https://github.com/custom-cards/bar-card/files/4455883/Screen.Recording.2020-04-09.at.13.29.59.zip)

The vertical bars represent covers.
While the position was changing, the bar had a cool animation that showed the movement of the cover.

I cannot reproduce it in version 3.  Now the bar just jumps in steps.  Not so cool.

[Screen Recording 2020-04-09 at 13.40.21.zip](https://github.com/custom-cards/bar-card/files/4455902/Screen.Recording.2020-04-09.at.13.40.21.zip)

Also, the position has moved up.  Can I have this in the middle as it was before?

This is the old config:

```
    align: center
    animation: auto
    attribute: current_position
    background: '#00FF00'
    background_style: false
    card_style: false
    charge_entity: false
    color: '#FF5555'
    columns: 6
    decimal: false
    delay: 5000
    direction: up
    entities:
      - entity: cover.kitchen_shutter
        title: Kitchen
      - entity: cover.dining_room_shutter
        title: Dining
      - entity: cover.stairs_shutter
        title: Stairs
      - entity: cover.bathroom_shutter
        title: Bath
      - entity: cover.basement_shutter
        title: Base
      - entity: switch.garden_lights
        title: .
    height: 100px
    icon: false
    icon_position: 'off'
    icon_style: false
    indicator: auto-vertical
    limit_value: false
    max: 100
    min: 0
    minmax_style: false
    padding: 4px
    rounding: 3px
    saturation: 50%
    severity: false
    show_minmax: false
    show_value: true
    speed: 1000
    tap_action: info
    target: false
    title: false
    title_position: bottom
    title_style: false
    type: 'custom:bar-card'
    unit_of_measurement: false
    value_style: false
    visibility: false
    width: 50%

```
This is the new config:

```
entities:
  - entity: cover.kitchen_shutter
    name: Kitchen
  - entity: cover.dining_room_shutter
    name: Dining
  - entity: cover.stairs_shutter
    name: Stairs
  - entity: cover.bathroom_shutter
    name: Bath
  - entity: cover.basement_shutter
    name: Base
  - entity: switch.garden_lights
    name: .
animation:
  - speed: 1000
  - delay: 5000
attribute: current_position
color: red
decimal: false
direction: up
height: 100px
max: 100
min: 0
positions:
  icon: 'off'
  indicator: inside
  title: outside
stack: horizontal
tap_action: info
type: 'custom:bar-card'
width: 50%

```

Thank you

**Comment by Gluwc** [comment]
You need to enable the animation.
```yaml
entities:
  - entity: cover.kitchen_shutter
    name: Kitchen
  - entity: cover.dining_room_shutter
    name: Dining
  - entity: cover.stairs_shutter
    name: Stairs
  - entity: cover.bathroom_shutter
    name: Bath
  - entity: cover.basement_shutter
    name: Base
  - entity: switch.garden_lights
    name: .
animation:
  state: 'on'
attribute: current_position
color: red
direction: up
height: 100px
max: 100
min: 0
positions:
  icon: 'off'
  indicator: inside
  title: outside
stack: horizontal
type: 'custom:bar-card'
width: 50%
```

For changing the position of the value you need to install [card-mod](https://github.com/thomasloven/lovelace-card-mod) and add:
```yaml
style: |-
  bar-card-value {
    margin-top: auto;
    margin-bottom: auto;
  }
```
