### ISSUE TITLE
Multiple entities, multiple config query

### ISSUE THREAD

**Issue by andystewart999** [custom-cards/bar-card#48]
Hi there - not an issue, just a query.

Your readme says that when using an entities array, it's possible to have config options for each defined entity:

"A list of entities. Accepts individual config options per defined entity."

What's the syntax for that?  I've tried a few, including this with a variety of indent attempts.
```
    entities:
      - sensor.sensor1
          color: '#00ba6a'
      - sensor.sensor2
          color: '#aabbcc'
```

Help!  My actual use case is to have two bars with two different colours.  I used to have two bar elements, but the new version has way larger margins so they're spaced out too far.

Cheers,
Andy

**Comment by Gluwc** [comment]
The entities config option itself is an array, so this is how you format it.
```yaml
    entities:
      - entity: sensor.sensor1
        color: '#00ba6a'
      - entity: sensor.sensor2
        color: '#aabbcc'
```
