### ISSUE TITLE
Background disapear after HA reboot using severity

### ISSUE THREAD

**Issue by lamirand-g** [custom-cards/bar-card#5]
When using a severity settings, it seems the order of value/color is important. However after HA reboot is always sort naturaly and so the bar-card is broken. If aI change back the order everything works as expected.

![image](https://user-images.githubusercontent.com/4324887/55782753-4251a600-5aad-11e9-944c-4a340e38e885.png)

```
- align: split
    entity: sensor.temperature_sda
    icon: 'mdi:thermometer'
    severity:
      - color: '#40bf40'
        value: 50
      - color: var(--label-badge-yellow)
        value: 60
      - color: '#bf4040'  
        value: 100              
    type: 'custom:bar-card'
```
