### ISSUE TITLE
severity for values not numbers

### ISSUE THREAD

**Issue by nicx** [custom-cards/bar-card#51]
Hi,

in older versions it was possible to use values instead of numbers in severities. In the documentation this is no more possible, but it still works:

```
  - type: custom:vertical-stack-in-card
    title: Batterien
    cards:
      - type: custom:auto-entities
        card:
          type: custom:bar-card
          attribute: battery
          unit_of_measurement: "V"
          positions:
            icon: 'off'
            indicator: 'off'
            title: inside
          min: 0
          max: 3.1
          color: Green
          severity:
          - color: Red
            from: 0
            to: 2.1
          - color: Orange
            from: 2.2
            to: 2.4
        filter:
          include:
          - attributes:
              battery: "<=100"
      - type: custom:auto-entities
        card:
          type: custom:bar-card
          attribute: battery
          unit_of_measurement: " "
          positions:
            icon: 'off'
            indicator: 'off'
            title: inside
          color: Green
          severity:
          - color: Red
            value: Low
        filter:
          include:
          - attributes:
              battery: Low
          - attributes:
              battery: High
```

Will this still work in future version? If yes: Please add this possibility to the documentation.

**Comment by Gluwc** [comment]
This is supposed to still work, however it might be broken with the new severity options. You can try setting the `from` and `to` values to the text value you want but I'm not sure if this will work.

I'm currently refactoring the card so I'll have a look for the next release.

**Comment by nicx** [comment]
already tried that: its not working ;)

**Comment by Gluwc** [comment]
That's what I thought, I'll try to fix it for the next release.

**Comment by Gluwc** [comment]
This should be fixed in [3.1.0b0](https://github.com/custom-cards/bar-card/releases/tag/3.1.0b0). Please note that this version might introduce some small new issues, but it will at least allow you to test the new `text` attribute for the severity array.
```yaml
severity:
  - text: Green
    color: green
  - text: Red
    color: red
```
