### ISSUE TITLE
Size problem when stacked (stack: horizontal)

### ISSUE THREAD

**Issue by Ndrinta** [custom-cards/bar-card#52]
I run into a little issue today:
![image](https://user-images.githubusercontent.com/4704172/79262535-66e31980-7e89-11ea-945d-4f958b97cc7b.png)
I don't know what to do in order to fix this... Any suggestion?

**Comment by Gluwc** [comment]
That's not good at all! I'll have a look for the next release.

**Comment by Gluwc** [comment]
Could you please show your config for this card so I can debug it?

**Comment by Ndrinta** [comment]
Sure, here you go!

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4704172/79278289-5344ac80-7ea3-11ea-86ce-939cc01599eb.gif)


```
animation:
  state: 'off'
decimal: 2
direction: up
entities:
  - entity: input_number.power_consuption_mon
    name: Mon
  - entity: input_number.power_consuption_tue
    name: Tue
  - entity: input_number.power_consuption_wed
    name: Wed
  - entity: input_number.power_consuption_thu
    name: Thu
  - entity: input_number.power_consuption_fri
    name: Fri
  - entity: input_number.power_consuption_sat
    name: Sat
  - entity: input_number.power_consuption_sun
    name: Sun
height: 150px
limit_value: false
max: 12
min: 0
positions:
  icon: 'off'
  indicator: inside
  title: outside
severity:
  - color: '#26BF8E'
    from: 0
    to: 5
  - color: '#FFA500'
    from: 5.001
    to: 8
  - color: '#FF6C4D'
    from: 8.001
    to: 100
stack: horizontal
style: |-
  bar-card-targetbar {
    visibility: hidden;
  }
target: 5
type: 'custom:bar-card'
unit_of_measurement: ' '
width: 100%

```

**Comment by Gluwc** [comment]
I think this might be because of the bar names being different widths. I'll see if I can do anything about this. 
For now maybe you would like to try the new [3.1.0b0](https://github.com/custom-cards/bar-card/releases/tag/3.1.0b0) beta (you can also enable the beta in HACS)? 
Your issue isn't fixed yet in this release, however it would be nice to have some beta testers =). Please note some features are still WIP and certain things might be slightly broken.

**Comment by Ndrinta** [comment]
I did join beta :) where do I find "documentation" for the beta features?

**Comment by Gluwc** [comment]
Sorry this currently isn't fixed in the beta. I'll have to have a look at this after I'm done with all the other bugs the new version is causing.

**Comment by Ndrinta** [comment]
Oh I'm sorry, wasn't to push you! I just wanted to let you know. Take all the time of this world! :)

**Comment by Gluwc** [comment]
Actually you can fix this right now by adding this to your style:

3.0.9
```css
  bar-card-title {
    margin: 0px -100%
  }
```
3.1.0b0
```css
  bar-card-name {
    margin: 0px -100%
  }
```
