### ISSUE TITLE
Card Margin

### ISSUE THREAD

**Issue by PierreScerri** [custom-cards/bar-card#54]
Hi

This is not an issue really but is there a way to change the margins indicated by the green arrows in the screenshot?

![Screenshot 2020-04-19 at 12 20 52](https://user-images.githubusercontent.com/34303331/79685450-314b8100-8239-11ea-84fd-2967413f5d4b.png)

Thank you.

```
animation:
  state: 'on'
attribute: current_position
color: red
decimal: false
direction: up
entities:
  - entity: cover.master_bedroom_shutter
    name: Master
  - entity: cover.front_bedroom_shutter
    name: Front
  - entity: cover.back_bedroom_shutter
    name: Back
  - entity: cover.sitting_room_front_shutter
    name: Front
  - entity: cover.sitting_room_door_shutter
    name: Door
  - entity: cover.sitting_room_back_shutter
    name: Back
height: 100px
max: 100
min: 0
positions:
  icon: 'off'
  indicator: inside
  title: outside
stack: horizontal
style: |-
  bar-card-value {
    margin-top: auto;
    margin-bottom: auto;
  }
tap_action: info
type: 'custom:bar-card'
width: 60%
```
