### ISSUE TITLE
BUG: Can't use margin css-style in bar-card-iconbar when position is inside since version 3.1.0

### ISSUE THREAD

**Issue by Klumpke** [custom-cards/bar-card#57]
Since bar-card version 3.1.0 it is no longer possible to use "bar-card-iconbar" margin css-style when icon postitions inside is set.

Before version 3.1.0 i used the code below to get my icons in the middle of the bar.
```yaml
bar-card-iconbar {
    color: white;
    margin-top: 80px;
}
```
And now they stay on top.
![afbeelding](https://user-images.githubusercontent.com/9717529/80277371-bf6ab000-86ee-11ea-9856-9a8a8fc49356.png)

**Comment by Gluwc** [comment]
This is an issue with the margin being hard coded for the iconbar. I'll fix this in the next release.

However if you want to center both the value and the icon I'd recommend doing something like this instead:

``` css
style: |-
  .value-direction-up {
    margin-top:  4px;
  }
  .contentbar-direction-up {
    justify-content: center;
  }
```
