### ISSUE TITLE
Severity not correct?

### ISSUE THREAD

**Issue by tomlut** [custom-cards/bar-card#6]
Maybe I am misunderstanding how severity works but I would have expected the following config:

```
      type: 'custom:bar-card'
      direction: right
      entity: sensor.pct_used_gb
      height: 30px
      max: 100
      min: 0
      severity:
        - value: 0
          color: '#0da035' # green
        - value: 75
          color: '#e0b400' # yellow
        - value: 90
          color: '#e45e65' # red
      title: NBN Data Used
      unit_of_measurement: '%'
```

To be green for a value of 6.6%. Instead it is yellow. https://i.imgur.com/J6RAPL6.png

**Comment by tomlut** [comment]
Never mind. I worked it out:
```
      type: 'custom:bar-card'
      direction: right
      entity: sensor.pct_used_gb
      height: 30px
      max: 100
      min: 0
      severity:
        - value: 75
          color: '#0da035' # green
        - value: 90
          color: '#e0b400' # yellow
        - value: 100
          color: '#e45e65' # red
      title: NBN Data Used
      unit_of_measurement: '%'
```
