### ISSUE TITLE
Card editing uses a lot of browser memory and does not release it

### ISSUE THREAD

**Issue by tomlut** [custom-cards/bar-card#63]
While editing the following card:

```
type: horizontal-stack
cards:
  - direction: right
    height: 30px
    max: '-100'
    min: '0'
    positions:
      icon: 'off'
      indicator: inside
      title: 'off'
      minmax: 'off'
      value: outside
    severity:
      - color: '#e45e65'
        from: '-100'
        to: '-80'
      - color: '#e0b400'
        from: '-80'
        to: '-68'
      - color: '#0da035'
        from: '-67'
        to: '0'
    style: |
      ha-card {
        border: solid 2px var(--primary-color);
      }
      bar-card-value {
        margin-right: auto;
      }
    type: 'custom:bar-card'
    unit_of_measurement: dBm
    value_style:
      color: var(--primary-text-color)
      text-shadow: none
    entities:
      - entity: sensor.bar_fridge_wifi_signal
        name: Bar Fridge
      - entity: sensor.bathroom_dht_wifi_signal
        name: Bathroom DHT
      - entity: sensor.cinema_av_wifi_signal
        name: Cinema AV
      - entity: sensor.cinema_subwoofer_wifi_signal
        name: Cinema Subwof
      - entity: sensor.comms_cupboard_dht_wifi_signal
        name: Comms Cbd
      - entity: sensor.comms_rack_wifi_signal
        name: Comms Rack
      - entity: sensor.dining_heater_north_wifi_signal
        name: Dining Heater N
      - entity: sensor.dining_heater_west_wifi_signal
        name: Dining Heater W
      - entity: sensor.dining_room_dht_wifi_signal
        name: Dining DHT
      - entity: sensor.dishwasher_wifi_signal
        name: Dishwasher
      - entity: sensor.doorbell_downstairs_wifi_signal
        name: Doorbell DN
      - entity: sensor.doorbell_upstairs_wifi_signal
        name: Doorbell UP
      - entity: sensor.ensuite_dht_wifi_signal
        name: Ensuite DHT
      - entity: sensor.fireplace_wifi_signal
        name: Fireplace
      - entity: sensor.fridge_wifi_signal
        nam: Fridge
      - entity: sensor.irrigation_wifi_signal
        name: Irrigation
      - entity: sensor.kitchen_leak_wifi_signal
        name: Kitchen Leak
      - entity: sensor.lane_gate_last_wifi
        name: Lane Gate
      - entity: sensor.laundry_leak_wifi_signal
        name: Laundry Leak
      - entity: sensor.led_table_wifi_signal
        name: LED Table
      - entity: sensor.lounge_av_wifi_signal
        name: Lounge AV
      - entity: sensor.lounge_chair_wifi_signal
        name: Lounge Chairr
    title: Wifi Signal Level
    target: '-67'
    animation:
      state: 'off'
  - direction: right
    height: 30px
    max: '-100'
    min: '0'
    positions:
      icon: 'off'
      indicator: inside
      title: 'off'
      minmax: 'off'
      value: outside
    severity:
      - color: '#e45e65'
        from: '-100'
        to: '-80'
      - color: '#e0b400'
        from: '-80'
        to: '-68'
      - color: '#0da035'
        from: '-67'
        to: '0'
    style: |
      ha-card {
        border: solid 2px var(--primary-color);
      }
      bar-card-value {
        margin-right: auto;
      }
    type: 'custom:bar-card'
    unit_of_measurement: dBm
    value_style:
      color: var(--primary-text-color)
      text-shadow: none
    entities:
      - entity: sensor.lounge_dehumidifier_wifi_signal
        name: Lounge Dehumid
      - entity: sensor.lounge_room_dht_wifi_signal
        name: Lounge DHT
      - entity: sensor.master_bed_sensor_wifi_signal
        name: Mstr Bed  Sensor
      - entity: sensor.master_bedroom_dht_wifi_signal
        name: MstrBed DHT
      - entity: sensor.mailbox_last_wifi
        name: Mailbox
      - entity: sensor.moisture_sensor_rssi
        name: Lawn Moisture
      - entity: sensor.outside_light_level_wifi_signal
        name: Outside Light LVL
      - entity: sensor.pc_monitor_wifi_signal
        name: PC Monitor
      - entity: sensor.rack_fan_wifi_signal
        name: Rack Fan
      - entity: sensor.roof_space_dht_wifi_signal
        name: Roof DHT
      - entity: sensor.rumpus_dehumidifier_wifi_signal
        name: Rumpus Dehumid
      - entity: sensor.rumpus_room_dht_wifi_signal
        name: Rumpus DHT
      - entity: sensor.spare_bed_sensor_wifi_signal
        name: Spr Bed Sensor
      - entity: sensor.spare_bedroom_dht_wifi_signal
        name: Spr Bed DHT
      - entity: sensor.spare_bedroom_heater_wifi_signal
        name: Spr Bed Heater
      - entity: sensor.spb_electric_blanket_wifi_signal
        name: Spr Bed Blanket
      - entity: sensor.washing_machine_wifi_signal
        name: Washing Machn
      - entity: sensor.workshop_critical_power_wifi_signal
        name: Workshop Pwr
      - entity: sensor.xmas_tree_lights_wifi_signal
        name: Xmas Lights
    title: Wifi Signal Level
    target: '-67'
    animation:
      state: 'off'
```
Firefox took 20 seconds to load the edit window and popped up "slow web page" warnings. After opening and closing the edit card dialogue a few times I noticed that firefox was using **10GB** of memory. The only way to get it to release this memory was to close firefox completely (not just the HA tab) and restart it.
