### ISSUE TITLE
Issue with Alignment

### ISSUE THREAD

**Issue by jhbcosta** [custom-cards/bar-card#67]
BarCardMinValue, BarCardMaxValue and BarCardValue are misaligned. Same code was OK on previous versions.

![image](https://user-images.githubusercontent.com/51212559/80598373-9eac9e00-89ff-11ea-99c9-9e48b2797e8f.png)

**Comment by jhbcosta** [comment]
Here is my code:

card:
  entities:
    - card:
        align: split
        columns: 1
        entity: sensor.peso_botijao
        height: 30px
        positions:
          icon: 'off'
          indicator: 'off'
          minmax: inside
          name: 'off'
          value: inside
        rounding: 0px
        severity:
          - color: '#bf4040'
            from: 0
            to: 30.99
          - color: '#ffc300'
            from: 31
            to: 59.99
          - color: '#40bf40'
            from: 60
            to: 100
        style: |-
          bar-card-value {
            margin-right: auto;
            margin-left: auto;
            margin-bottom: auto;
            margin-top: -8px;
            font-size: 14px
          }
          bar-card-min {
            margin-top: 16px;
            margin-left: 8px;
            margin-right: auto;
            margin-bottom: -13px;
            bottom: 8px;
          }
          bar-card-max {
            margin-bottom: 0px;
            margin-right: 8px;
            margin-left: auto;
            margin-top: -13px;
            top: 6px;
          }
          bar-card-divider {
            display: none;
          }
          bar-card-contentbar {
            flex-direction: column;
          }
          bar-card-title {
            margin-bottom: 0px;
          }
        title_position: inside
        title_style:
          font-size: 14px
        type: 'custom:bar-card'
        unit_of_measurement: '%'
        value_style:
          font-size: 12px
        width: 100%
      type: 'custom:auto-entities'
  type: entities
style:
  border: solid 2px var(--primary-color)
  border-radius: 10px
  transform: scale(1.00)
type: 'custom:card-modder'

**Comment by Gluwc** [comment]
Some of the elements have changed a bit and the example is a bit outdated. Try something like this:

```yaml
positions:
  icon: 'off'
  indicator: 'off'
  minmax: inside
  title: inside
  value: inside
style: |-
  .contentbar-direction-right {
   flex-direction: column;
  }
  .min-direction-right {
    margin: 0px;
    margin-left: 4px;
    margin-right: auto;
    margin-bottom: -20px;
    bottom: 10px;
  }
    bar-card-value {
    margin: 0px;
  }
  bar-card-name {
    margin: 0px;
  }
  bar-card-max {
    margin: 0px;
    margin-left: auto;
    margin-top: -20px;
    top: 10px;
  }
  bar-card-divider {
    display: none;
  }
title: Custom CSS Layout
type: 'custom:bar-card'
entities:
  - entity: sensor.example
```
