### ISSUE TITLE
When no symbol is displayed then give the space free

### ISSUE THREAD

**Issue by Pirol62** [custom-cards/bar-card#68]
I have set all symbols and values to off or inside.
The space around the bar is anyway not reduced and therefore I do not win space.
I would prefer to fill that with additional bar size.
![image](https://user-images.githubusercontent.com/48820003/80611240-a8072c00-8a3a-11ea-9138-91087845fb59.png)

**Comment by Gluwc** [comment]
Have you tried setting the `icon` position to `off`? This area is where the icon is normally displayed but if you have no icon defined it shows an empty space unless you disable the icon.

**Comment by Pirol62** [comment]
````
direction: up
height: 100px
name: 'black '
positions:
  icon: 'off'
severity:
  - color: Red
    from: 0
    to: 20
  - color: Orange
    from: 21
    to: 50
  - color: Green
    from: 51
    to: 100
type: 'custom:bar-card'
entities:
  - entity: sensor.hp_officejet_pro_8710_black_ink
````
Thats my config.
