### ISSUE TITLE
Populate values from templates

### ISSUE THREAD

**Issue by pkissling** [custom-cards/bar-card#69]
Hi,

just wanted to ask if it's possible to populate values using templates.

Use case:
I want to populate the value of `target` from a sensor.
```yaml
# Temperature
- type: custom:bar-card
  entities:
    - entity: sensor.bathroom_temperature
      icon: mdi:shower
      target: "{{ states('sensor.bathroom_target_temperature') }}"
  min: 18
  max: 25
  decimal: 1
```

This would allow me to show the target temperature for a room dynamically.

Thanks in advance!
