### ISSUE TITLE
Barchart bars are not the same width.

### ISSUE THREAD

**Issue by zibous** [custom-cards/bar-card#76]
**Installed:  BAR-CARD   Version 3.1.6**  

![Bildschirmfoto 2020-05-03 um 15 08 22](https://user-images.githubusercontent.com/30198737/80915265-68e61d00-8d51-11ea-81bf-dd54521d7a2e.png)

```yaml
type: "custom:vertical-stack-in-card"
title: Verbrauch Erdgeschoss
cards:

  - type: "custom:bar-card"
    columns: 7
    stack: horizontal
    direction: up
    entities:
      - entity: sensor.verbrauch_buro
        name: 'Büroraum'
      - entity: sensor.verbrauch_waschraum
        name: 'Wirtschaftraum'
      - entity: sensor.verbrauch_heizung
        name: 'Heizungsraum'
      - entity: sensor.verbrauch_vorratsraum
        name: 'Vorratsraum'
      - entity: sensor.verbrauch_gang_eg
        name: 'Vorraum'
      - entity: sensor.verbrauch_garage
        name: 'Garage'
      - entity: sensor.verbrauch_zahlerschrank
        name: 'Zählerschrank'
    positions:
      icon: 'off'
      indicator: inside
      name: outside
    height: 240px
    max: 3500
    min: 0
    padding: 2px
    title_position: inside
    unit_of_measurement: Wh
    width: 100%
    line_width: 0.5
    title_style:
      font-size: 14px
      font-weight: 400
    value_style:
      font-size: 14px
      font-weight: 500
    severity:
      - color: "#CFD8DC"
        value: 0
      - color: "#4CAF50"
        value: 50
      - color: "#FDD835"
        value: 100
      - color: "#64DD17"
        value: 200
      - color: "#FFF176"
        value: 300
      - color: "#FFEB3B"
        value: 400
      - color: "#FF5722"
        value: 600
      - color: "#f44336"
        value: 800
      - color: "#f44336"
        value: 5000
    style: |
      ha-card {
        border-radius: 4px;
        transform: scale(0.95);
        background-size: 100% 100%;
        background-color: transparent;
      }
     ....
```

Do I have to change anything in the settings?
