### ISSUE TITLE
Target cannot be set to dynamic entity

### ISSUE THREAD

**Issue by UbhiTS** [custom-cards/bar-card#77]
Great Card, love it !!! however, in v2 the target was settable to an entity state value. But that's not the case with v3. Can that be fixed to work like it used to.

```yaml
- type: custom:bar-card
  columns: 4
  height: 178px
  title_position: bottom
  direction: up
  indicator: off
  positions:
    icon: inside
    name: outside
    indicator: 'off'
  entities:
    - entity: sensor.powerwall_power
      name: "batt"
      target: sensor.powerwall_bar_target # THIS DOES NOT WORK
      min: 0
      max: 8
      icon: mdi:car-battery
      severity:
        - color: 'green'
          from: 0
          to: 10
```

**Comment by Gluwc** [comment]
This is no longer directly possible, however you can use [config-template-card](https://github.com/iantrich/config-template-card) to get the same result.

**Comment by UbhiTS** [comment]
worked perfectly. Thank you :)

**Comment by Abbadon89** [comment]
Can you please share correct code to solve that problem?

**Comment by UbhiTS** [comment]
```yaml
cards:
                  - type: "custom:config-template-card"
                    entities:
                      - sensor.solar_power
                      - sensor.grid_power
                      - sensor.grid_bar_target
                      - sensor.powerwall_power
                      - sensor.powerwall_bar_target
                      - sensor.house_load
                    card:
                      # HOUSE ENERGY PROFILE BARS
                      type: custom:bar-card
                      columns: 4
                      title_position: bottom
                      direction: up
                      positions:
                        icon: inside
                        name: outside
                        value: outside
                        indicator: 'off'
                      animation:
                        state: 'on'
                        speed: 5
                      entities:
                        - entity: sensor.solar_power
                          name: "solar"
                          target: "${states['sensor.solar_power'].state}"
                          min: 0
                          max: 8
                          icon: mdi:weather-sunset
                          severity:
                            - color: 'yellow'
                              from: 0
                              to: 8
                        - entity: sensor.grid_power
                          name: "grid"
                          target: "${states['sensor.grid_bar_target'].state}"
                          min: 0
                          max: 8
                          icon: mdi:transmission-tower
                          severity:
                            - color: 'orange'
                              from: -8
                              to: 8
                        - entity: sensor.powerwall_power
                          name: "batt"
                          target: "${states['sensor.powerwall_bar_target'].state}"
                          min: 0
                          max: 8
                          icon: mdi:car-battery
                          severity:
                            - color: 'green'
                              from: -8
                              to: 8
                        - entity: sensor.house_load
                          name: "load"
                          target: "${states['sensor.house_load'].state}"
                          min: 0
                          max: 8
                          icon: mdi:home
                          severity:
                            - color: 'red'
                              from: 0
                              to: 8
                      # HOUSE ENERGY PROFILE BARS
```
