### ISSUE TITLE
Tap action not working.

### ISSUE THREAD

**Issue by PierreScerri** [custom-cards/bar-card#83]
I just noticed that tap_action: info is not working.

On touch devices (iPhone X, Amazon FireHD10) a long press brings up the 'More info' box.  The card does not work on iPad iOS10).

```
animation:
  state: 'on'
attribute: current_position
color: red
decimal: false
direction: up
entities:
  - entity: cover.master_bedroom_shutter
    name: Master
  - entity: cover.front_bedroom_shutter
    name: Front
  - entity: cover.back_bedroom_shutter
    name: Back
  - entity: cover.sitting_room_front_shutter
    name: Front
  - entity: cover.sitting_room_door_shutter
    name: Door
  - entity: cover.sitting_room_back_shutter
    name: Back
height: 120px
max: 100
min: 0
positions:
  icon: 'off'
  indicator: inside
  name: outside
  title: outside
stack: horizontal
style: |-
  bar-card-value {
    margin-top: auto;
    margin-bottom: auto;
  }
  #states {
    padding: 0px 5px;
  }
tap_action: info
type: 'custom:bar-card'
width: 60%

```

**Comment by Abbadon89** [comment]
+1 
```
 tap_action: service
 service_options:
   domain: input_boolean
   service: toggle
   data:
     entity_id: input_boolean.mini_dysk
```
