### ISSUE TITLE
Use entity value for target, max value

### ISSUE THREAD

**Issue by Gunth** [custom-cards/bar-card#88]
Hi there,

I saw on this reply (https://community.home-assistant.io/t/lovelace-bar-card/87503/77) that the version 0.1.0 enable the possibility to use an entity as max value.
But when i try to use this feature, it doesn't seems to work, it show NaN.
Here is my current configuration :
```
type: 'custom:bar-card'
entities:
  - entity: sensor.sma_current_month_production
    limit_value: true
unit_of_measurement: kWh
max: sensor.sma_last_month_production
```

I'm using use the latest version 3.1.6

Thanks.
