### ISSUE TITLE
Request: Conditional Icons

### ISSUE THREAD

**Issue by grahamPegNetwork** [custom-cards/bar-card#89]
Suggestion/request: Allow for icon based on another entity's status, like conditional cards.
eg:
```
  - entity: input_number.laptopbattery
       icon_condition_entity:
         person.user
         condition_name: "zone"
         condition_icon: "mdi:home"
```
This would rely on the default entity icon, but if the specified entity's condition matched, would use the specified icon.

Eg: I use laptop/phone icons with bars displaying their battery level. If I specify their status entity as a condition I would like to display a charging icon instead.
