### ISSUE TITLE
Feature request. Make it possible to use template for the name.

### ISSUE THREAD

**Issue by bessarabov** [custom-cards/bar-card#92]
I'm using this card and I'm very happy with it, but one thing is missing for my use cases.

I want to show name on the bar card that is stored in some other `input_text, but I can't find a way to do it. I've tried using a template:

```
      - type: 'custom:bar-card'
        entities:
          - entity: sensor.water_filter_1_usage
            name: '{{ states(''input_text.water_filter_1_name'') }}'
```

but this just shows the text as-is:

![Screenshot 2020-07-05 at 20 50 57](https://user-images.githubusercontent.com/47263/86538862-42836000-bf01-11ea-9547-6cc30fdf7d26.png)

What do you think about changing the logic for the `name` field? To allow entering templates there?
