### ISSUE TITLE
Icon for title ?

### ISSUE THREAD

**Issue by zibous** [custom-cards/bar-card#97]
Is there a way to add an icon to the title?

![Bildschirmfoto 2020-08-01 um 11 04 42](https://user-images.githubusercontent.com/30198737/89098425-c852d800-d3e7-11ea-95c3-346f36d136de.png)

```yaml
type: "custom:bar-card"
entities:
  - entity: sensor.wasser_liter_h
    name: Jetzt
    min: 0.0
    max: 70.0
  - entity: sensor.wasser_liter_tag
    name: Heute
    min: 0.0
    max: 240.0
  - entity: sensor.wasser_liter_monat
    name: Monat
    min: 0.0
    max: 520.0
  - entity: sensor.wasser_liter_jahr
    name: Jahr
    min: 0.0
    max: 120000.0
title: Wasserverbrauch
icon: mdi:waves.   <<---- ???
direction: up
height: 150px
width: 75%
stack: horizontal
animation: auto
positions:
  icon: inside
  indicator: inside
  name: outside
  title: outside
style: |
  ha-card{
      transform: scale(0.96);
      background-size: 100% 100%;
  }
  .card-header{
     padding: 6px 20px;
     font-size: 1.4em;
     text-align: left;
     color: #007aff;
  }
  .graph__legend { flex-wrap: nowrap; }
  #states {  padding: 24px 24px; }
  bar-card-value { font-size: 0.9em }
  bar-card-current, bar-card-backgroundbar, bar-card-currentbar {
    border-radius: 0 0 1.6em 1.6em;
  }
```
