### ISSUE TITLE
[Feature request] Enhancing bar-card capability of managing 'history_stats'

### ISSUE THREAD

**Issue by liuk4friends** [custom-cards/bar-card#99]
Bar-card works flawlessy with 'history_stats' but, as you probably know, 'history_stats' reports time in a strange way.
If I'm not wrong, 'history_stats' reports minutes in a decimal way.
For instance, when 'history_stats' reports '1.91h', the correct time format should be '01:54' (one hour and fifty-four minutes)

So, we are forced to use a template for converting '1.91h' to a more readable format, ie '01h 54m'.

An example below:
```
  - platform: template
    sensors:
      luca_time_at_home_readable:
        friendly_name: "Luca tempo in casa (leggibile)"
        entity_id: sensor.luca_time_at_home
        value_template: "{{ state_attr('sensor.luca_tempo_in_casa', 'value')}}"
```

If I configure 'bar-card' with this template, the result is that 'bar-card' doesn't show the correct amount of time.
I'm attaching two screenshot because "a picture is worth more than a thousand words"

![Screeny Shot 9 Aug 2020 at 22 18 31](https://user-images.githubusercontent.com/63516851/89741120-cdbabd00-da8e-11ea-8caf-153faf9bc2ce.png)

![Screeny Shot 9 Aug 2020 at 22 18 57](https://user-images.githubusercontent.com/63516851/89741123-d57a6180-da8e-11ea-9599-2e247dd68cfd.png)

So, I wonder if in the future 'bar-card' will be able to handle the 'standard time format' correctly.
I would like to stress that your custom-card is superb!
Thank you in advance,
Luca
